### ISSUE TITLE
Need more info when another use is logged in

### ISSUE THREAD

**Issue by wdmillard** [pacifica/pacifica-legacy-uploader#1]
When I attempt to access an uploader and it is being used by another user I get the message
"Another use is currently logged in".  
This is not very informative.  I would like to know the name of the user that is logged in.

The may become OBE when we provide a multi-user Uploader, then this won't happen.

**Comment by dmlb2000** [comment]
This is the legacy Go Autouploader you probably meant to put this in https://github.com/EMSL-MSC/pacifica-uploader
